### ISSUE TITLE
Leaks checking

### ISSUE THREAD

**Issue by tevaaa** [Tripouille/gnlTester#12]
The tester indicate leaks whereas system leaks and valgrind dont find leaks with the same inputs parameters

**Comment by gpiriou** [comment]
I confirm.

**Comment by gpiriou** [comment]
I have the same issue.

**Comment by smwkbgmn** [comment]
I'm getting through the same issue on the M1 pro mac.

**Comment by DanielAJL** [comment]
Seems like I'm encountering the same issue.

**Comment by Tripouille** [comment]
Can you provide some screenshots ? If I remember correctly, my tester will show leaks if you forget to free a value which is not the case for valgrind. If you still have a pointer to an unused value this is ok for valgrind even if you don't use it anymore.

**Comment by DanielAJL** [comment]
@Tripouille Here is a screenshot of what I expected to be a fully successful run:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/56198192/218255158-75e1707e-8908-4a20-a27e-7edaf7a3b5a6.png">

And here is a screenshot of one where I purposely commented out free()'s in my program:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/56198192/218255203-b2c56bf1-0bdf-46be-abd7-0f418407b675.png">

**Comment by DanielAJL** [comment]
@Tripouille 

I actually take back my comment, it **does** indeed work.
It was really hard to find what was giving me the leaks, but eventually it was  specifically a free() needed for if we reached the last call.

**Comment by Tripouille** [comment]
Thanks for your feedback on the issue @DanielAJL .
Since everything seems okay, I close this issue.
