### ISSUE TITLE
Too early leak testing in the bonus part

### ISSUE THREAD

**Issue by ayeCaptainJack** [Tripouille/gnlTester#4]
In the bonus part more precisely in the multiple-fd testing the showLeaks() function is getting called before the get_next_line function actually finishes (in case it returns NULL). Therefore it shows leaks if you still have heap-allocated memory when you return the last line which isn't correct, because get_next_line only finishes if it returns NULL. The tester should let get_next_line read all filedescriptors until the function returns null.

**Comment by Tripouille** [comment]
![](https://media3.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif)
